### ISSUE TITLE
Value Error for TensorFlowV2Classifier in extraction attack running on MNIST data

### ISSUE THREAD

**Issue by vincentliuheyang** [Trusted-AI/adversarial-robustness-toolbox#1172]
Hi

I am implementing the extraction attacks (Probabilistic CopycatCNN, Argmax CopycatCNN, Probabilistic KnockoffNets, Argmax KnockoffNets) on TensorFlowV2Classifier. I am trying to test it on MNIST data with a two-layered CNN model implementing the tf-keras model. It tells me that I got a value error which I have no clue why.

`
ValueError: Shape mismatch: The shape of labels (received (320,)) should equal the shape of logits except for the last dimension (received (32, 10)).
`

I had set batch size 32 and have not done any reshape, tried to debug the code and I find the problem occurs at the `fit` class of `TensorFlowV2Classifier` class, which is 

```
for _ in range(nb_epochs):
        for images, labels in train_ds:
                self._train_step(self.model, images, labels)
```

I cannot find which variables turns my label shape into `(320,)`, but when I finish running the train_step method, it automatically returns this error. Can you check this out because I do not think my code is doing anything wrong here. Thanks a lot

**Comment by beat-buesser** [comment]
Hi @vincentliuheyang Thank you very much for using ART!

We would need more information to find out what is happening, could you please provide a complete example that reproduces your observation?

**Comment by vincentliuheyang** [comment]
I am using tf2.0 keras model and pretty much follow the method in your repo

```
        vm = VictimModel(self.trainx, self.trainy, self.testx, self.testy, im_shape=im_shape, epochs=epochs, batch_size=batch_size, num_classes=num_classes, c1=c1, c2=c2, d1=d1)
             self.victim_model = TensorFlowV2Classifier(vm.model, nb_classes=num_classes, input_shape=im_shape, clip_values=(0, 1), train_step=train_step)
        self.attack_catalogue = {"Probabilistic CopycatCNN": CopycatCNN(classifier=self.victim_model,
                                                                        batch_size_fit=batch_size,
                                                                        batch_size_query=64,
                                                                        nb_epochs=num_epochs,
                                                                        nb_stolen=trainx.shape[0],
                                                                        use_probability=True),
                                   "Argmax CopycatCNN": CopycatCNN(classifier=self.victim_model,
                                                                   batch_size_fit=batch_size,
                                                                   batch_size_query=64,
                                                                   nb_epochs=num_epochs,
                                                                   nb_stolen=trainx.shape[0],
                                                                   use_probability=False),
                                   "Probabilistic KnockoffNets": KnockoffNets(classifier=self.victim_model,
                                                                              batch_size_fit=batch_size,
                                                                              batch_size_query=64,
                                                                              nb_epochs=num_epochs,
                                                                              nb_stolen=trainx.shape[0],
                                                                              use_probability=True),
                                   "Argmax KnockoffNets": KnockoffNets(classifier=self.victim_model,
                                                                       batch_size_fit=batch_size,
                                                                       batch_size_query=64,
                                                                       nb_epochs=num_epochs,
                                                                       nb_stolen=trainx.shape[0],
                                                                       use_probability=False),
                                   }

        self.classifier_stolen = None
        self.dir = None

    def fit(self, name):
        attack = self.attack_catalogue[name]
        self.classifier_stolen = attack.extract(self.trainx, self.trainy, thieved_classifier=self.victim_model)
```


Here is my code to execute the attack model

```
attack = ["Probabilistic CopycatCNN", "Argmax CopycatCNN", "Probabilistic KnockoffNets", "Argmax KnockoffNets"]

    
WBAM = White_Box_Attack_Model(x_steal, y_steal)

for a in attack:
    WBAM.fit(a)
    print(WBAM.evaluate())
```

And when I am executing this method, it gives me this error
```
\venv\lib\site-packages\tensorflow\python\keras\backend.py:4930: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a sigmoid or softmax activation and thus does not represent logits. Was this intended?"
  '"`sparse_categorical_crossentropy` received `from_logits=True`, but '
Traceback (most recent call last):
  File "/privacy-top/msa/test_attack.py", line 33, in <module>
    WBAM.fit(a)
  File "\privacy-top\msa\attack_model.py", line 94, in fit
    self.classifier_stolen = attack.extract(self.trainx, self.trainy, thieved_classifier=self.victim_model)
  File "\venv\lib\site-packages\art\attacks\attack.py", line 75, in replacement_function
    return fdict[func_name](self, *args, **kwargs)
  File "\venv\lib\site-packages\art\attacks\extraction\copycat_cnn.py", line 123, in extract
    nb_epochs=self.nb_epochs,
  File "\venv\lib\site-packages\art\estimators\classification\classifier.py", line 71, in replacement_function
    return fdict[func_name](self, *args, **kwargs)
  File "\venv\lib\site-packages\art\estimators\classification\tensorflow.py", line 962, in fit
    self._train_step(self.model, images, labels)
  File "\venv\lib\site-packages\tensorflow\python\eager\def_function.py", line 889, in __call__
    result = self._call(*args, **kwds)
  File "\venv\lib\site-packages\tensorflow\python\eager\def_function.py", line 933, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "\venv\lib\site-packages\tensorflow\python\eager\def_function.py", line 764, in _initialize
    *args, **kwds))
  File "\venv\lib\site-packages\tensorflow\python\eager\function.py", line 3050, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "\venv\lib\site-packages\tensorflow\python\eager\function.py", line 3444, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "\venv\lib\site-packages\tensorflow\python\eager\function.py", line 3289, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "\venv\lib\site-packages\tensorflow\python\framework\func_graph.py", line 999, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "\venv\lib\site-packages\tensorflow\python\eager\def_function.py", line 672, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "\venv\lib\site-packages\tensorflow\python\framework\func_graph.py", line 986, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    \privacy-top\msa\attack_model.py:20 train_step  *
        loss = loss_fn(labels, predictions)
    \venv\lib\site-packages\tensorflow\python\keras\losses.py:155 __call__  **
        losses = call_fn(y_true, y_pred)
    \venv\lib\site-packages\tensorflow\python\keras\losses.py:259 call  **
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    \venv\lib\site-packages\tensorflow\python\util\dispatch.py:206 wrapper
        return target(*args, **kwargs)
    \venv\lib\site-packages\tensorflow\python\keras\losses.py:1713 sparse_categorical_crossentropy
        y_true, y_pred, from_logits=from_logits, axis=axis)
    \venv\lib\site-packages\tensorflow\python\util\dispatch.py:206 wrapper
        return target(*args, **kwargs)
    \venv\lib\site-packages\tensorflow\python\keras\backend.py:4980 sparse_categorical_crossentropy
        labels=target, logits=output)
    \venv\lib\site-packages\tensorflow\python\util\dispatch.py:206 wrapper
        return target(*args, **kwargs)
    \venv\lib\site-packages\tensorflow\python\ops\nn_ops.py:4229 sparse_softmax_cross_entropy_with_logits_v2
        labels=labels, logits=logits, name=name)
    \venv\lib\site-packages\tensorflow\python\util\dispatch.py:206 wrapper
        return target(*args, **kwargs)
    \venv\lib\site-packages\tensorflow\python\ops\nn_ops.py:4136 sparse_softmax_cross_entropy_with_logits
        logits.get_shape()))

    ValueError: Shape mismatch: The shape of labels (received (320,)) should equal the shape of logits except for the last dimension (received (32, 10)).
```
I am setting batch size to be 32 so it should give me a shape of (32,10), but it turns out here saying the label is shape of (320,), I traced down to see which code went wrong, and I saw this line of code is not running correctly, 

```
# File: venv\Lib\site-package\art\estimators\classification\tensorflow.py
# class TensorFlowV2Classifier(ClassGradientsMixin, ClassifierMixin, TensorFlowV2Estimator):
#   def fit(self, x: np.ndarray, y: np.ndarray, batch_size: int = 128, nb_epochs: int = 10, **kwargs) -> None:

         for _ in range(nb_epochs):
              for images, labels in train_ds:
                  self._train_step(self.model, images, labels)
```

**Comment by beat-buesser** [comment]
How do you define the method `train_step`?

Would it be possible for you to put the example into a Google Colab notebook, that way we could try it out?

**Comment by vincentliuheyang** [comment]
I basically defined the train step function the way as tf.keras did, here is the function

```
def train_step(model, images, labels):
    optimizer=tf.keras.optimizers.SGD(learning_rate=1e-3)
    loss_fn=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
    train_loss = tf.keras.metrics.Mean(name='train_loss')
    train_acc_metric = tf.keras.metrics.SparseCategoricalAccuracy(name='train_accuracy')

    with tf.GradientTape() as tape:
        predictions = model(images)
        loss = loss_fn(labels, predictions)
    gradients = tape.gradient(loss, model.trainable_variables)
    optimizer.apply_gradients(zip(gradients, model.trainable_variables))

    train_loss(loss)
    train_acc_metric(labels, predictions)
    return loss
```

I think I can put it into a google Colab, how should I share the link with you guys?

**Comment by beat-buesser** [comment]
I'm still not able to run the example, e.g. arguments of `VictimModel` are missing. Would you have a complete example that I could run?

**Comment by vincentliuheyang** [comment]
I packed the VictimModel with a CNN model, here is the structure

```
class VictimModel:
    def __init__(self,
                 trainx,
                 trainy,
                 testx,
                 testy,
                 im_shape=(28,28,1),
                 epochs=10,
                 batch_size=32,
                 num_classes=10,
                 c1=32,
                 c2=64,
                 d1=128
                 ):
        self.testx = testx
        self.testy = testy
        self.epochs = epochs
        self.batch_size = batch_size
        self.model = Sequential()
        self.model.add(Conv2D(c1, kernel_size=(3, 3), activation='relu', kernel_initializer='he_uniform', input_shape=im_shape))
        self.model.add(BatchNormalization())
        self.model.add(Dropout(0.2))
        self.model.add(Conv2D(c2, (3, 3), activation='relu', kernel_initializer='he_uniform'))
        self.model.add(BatchNormalization())
        self.model.add(Dropout(0.2))
        self.model.add(Flatten())
        self.model.add(Dense(d1, activation='relu', kernel_initializer='he_uniform'))
        self.model.add(Dense(num_classes, activation='softmax'))
        self.dir = dir
        self.model_file = model_file

    def fit(self, checkpoint_path="target.cpkt"):
        history = self.model.compile(loss=tf.keras.losses.categorical_crossentropy, optimizer="sgd", metrics=['accuracy'])
        self.model.fit(self.trainx, self.trainy, epochs=self.epochs, callbacks=[callback], batch_size=self.batch_size, validation_data=(self.valx, self.valy))
        return history
```

**Comment by beat-buesser** [comment]
Hi @vincentliuheyang Would you have a complete end-to-end example that I could easily run without modifications?

**Comment by vincentliuheyang** [comment]
I have attached everything here in this repository, can you please check this problem out. [https://github.com/vincentliuheyang/ART-Issue/blob/main/adversarial_training.ipynb](url)

**Comment by beat-buesser** [comment]
Hi @vincentliuheyang There are some changes required to your code:
- your model predicts probabilities, therefore the loss functions should receive `from_logits=False`
- don't define the optimizer inside of `train_step` because the optimizer will be reset every step, follow `examples/get_started_tensorflow_v2.py`
- don't define the loss function inside of `train_step` because `TensorFlowV2Classifier` will not know which loss function, and especially which label format, you are using, provide the loss function to the argument `loss_object` instead
- the thieved model and the victim model cannot be the same instance (`thieved_classifier=self.victim_model`), create separate classifier instances instead.

**Comment by vincentliuheyang** [comment]
Thank you, the problem is solved.
