### ISSUE TITLE
UnboundLocalError: local variable 'archive' referenced before assignment????

### ISSUE THREAD

**Issue by zhangshuaizxc** [Trusted-AI/adversarial-robustness-toolbox#811]
Traceback (most recent call last):
  File "/tmp/pycharm_project_988/lianshou/awd.py", line 135, in <module>
    (x_train, y_train), (x_test, y_test), min_, max_ = load_dataset(str("cifar10"))
  File "/usr/local/lib/python3.6/dist-packages/art/utils.py", line 959, in load_dataset
    return load_cifar10()
  File "/usr/local/lib/python3.6/dist-packages/art/utils.py", line 692, in load_cifar10
    url="http://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz",
  File "/usr/local/lib/python3.6/dist-packages/art/utils.py", line 1077, in get_file
    _extract(full_path, path_)
  File "/usr/local/lib/python3.6/dist-packages/art/utils.py", line 987, in _extract
    archive.extractall(path)
UnboundLocalError: local variable 'archive' referenced before assignment

**Comment by beat-buesser** [comment]
Hi @zhangshuaizxc Could you please check of the file `http://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz` has been downloaded correctly? With default settings it should exist locally as "~/.art/data/cifar-10-batches-py.tar.gz"
