### ISSUE TITLE
Simba: ValueError: could not broadcast input array from shape (3,301,7) into shape (3,299,5)

### ISSUE THREAD

**Issue by Code-Ranger** [Trusted-AI/adversarial-robustness-toolbox#924]
**Describe the bug**
Hello,
While I am working on using SimBA for black-box evision attacking based on the example code from https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/notebooks/classifier_blackbox.ipynb , but got Value Error as following.

**To Reproduce**
1. based on the example code of https://github.com/Trusted-AI/adversarial-robustness-toolbox/blob/main/notebooks/classifier_blackbox.ipynb
2. create blackbox object from BlackBoxClassifierNeuralNetwork
3. change the black-box attacking method to SimBA 
See error

Traceback (most recent call last):
  File "/home/ranger/home/ranger/lizhu/src/art/simba.py", line 93, in <module>
    x_adv = attack.generate(x=np.array([target_image]), x_adv_init=x_adv)
  File "/home/ranger/tools/anaconda/lib/python3.8/site-packages/art/attacks/attack.py", line 74, in replacement_function
    return fdict[func_name](self, *args, **kwargs)
  File "/home/ranger/tools/anaconda/lib/python3.8/site-packages/art/attacks/evasion/simba.py", line 139, in generate
    indices = self._block_order(x.shape[2], nb_channels, initial_size=self.freq_dim, stride=self.stride)[
  File "/home/ranger/tools/anaconda/lib/python3.8/site-packages/art/attacks/evasion/simba.py", line 306, in _block_order
    order[:, : (i + stride), i : (i + stride)] = perm[:num_first].reshape((channels, -1, stride))
ValueError: could not broadcast input array from shape (3,301,7) into shape (3,299,5)

**Comment by beat-buesser** [comment]
Hi @Code-Ranger Thank you very much for raising this issue. Could you please provide more details how you are creating the instance of `BlackBoxClassifierNeuralNetwork` and describe the dataset?

**Comment by Code-Ranger** [comment]
Hello, beat-buesser
Thanks very much for supporting!
The image I used for black-box attacking is the one from ImageNet ![unicycle](https://user-images.githubusercontent.com/13929749/109904391-1f9b8c80-7cd8-11eb-9b66-bf2a5947e45b.jpg)
And please find the major part of my code in below:

···
# Preprocess transform the np array image into tensor
preprocess = torchvision.transforms.Compose([
    torchvision.transforms.CenterCrop(224),
    torchvision.transforms.ToTensor(),
    torchvision.transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])

# load the pre-trained model
resnet = torchvision.models.resnet152(pretrained=True)
predict_counter = 0

# define predict function that reformats inputs, connects to wml scoring endpoint and returns one-hot encoded predictions
def predict(x):
    global predict_counter
    predict_counter += 1

    x = np.array(x[0])
    # convert np array back to image
    img = Image.fromarray(x.astype(np.uint8))
    img_t = preprocess(img)
    batch_t = torch.unsqueeze(img_t, 0)
    resnet.eval()
    out = resnet(batch_t)

    _, index = torch.max(out, 1)
    one_hot = np.zeros(out.shape[1])
    one_hot[index] = 1
    return one_hot

# Create blackbox object
classifier = BlackBoxClassifierNeuralNetwork(predict, image_array[0].shape, 1000, channels_first=False, clip_values=(0, 255))

# Select target image and check the prediction
target_image = image_array[0]
plt.imshow(Image.fromarray(target_image.astype(np.uint8)))
plt.show(block=False)
prediction = str(np.argmax(classifier.predict(image_array[:1], batch_size=image_array[0].shape[0]), axis=1)[0])
print("Prediction is: %s " % prediction, str(classes[prediction]))


# Generate HopSkipJump attack against black box classifier
attack = SimBA(classifier=classifier, max_iter=args.iter, freq_dim=args.freq_dim, order=args.order, stride=args.stride)
x_adv = None
for i in range(10):
    x_adv = attack.generate(x=np.array([target_image]), x_adv_init=x_adv)

    prediction = str(np.argmax(classifier.predict(x_adv)[0]))
    print("Adversarial image at step %d." % i, "L2 error",
          np.linalg.norm(np.reshape(x_adv[0] - target_image, [-1])),
          "and class label is %s " % prediction, str(classes[prediction]))

    plt.imshow(Image.fromarray(x_adv[0].astype(np.uint8)))
    plt.show(block=False)

    print("Total number of predict() has been called: ", predict_counter)
···

**Comment by beat-buesser** [comment]
Hi @Code-Ranger I have been able to run your code above with ART 1.5.2 using the following arguments: `args.iter_ = 30`, `args.freq_dim = 4`, `args.order = "random"`, and `args.stride = 1`.

Which version of ART are you using?

**Comment by Code-Ranger** [comment]
Hello @beat-buesser 
Thanks for supporting!
I am using V1.5.2
Just tried with the arguments you recommended. The SimBA can run, but the result image can still be classified as Unicycle by ResNet. It looks like the evision is not working

**Comment by beat-buesser** [comment]
Hi @Code-Ranger Ok, now I see, it's a similar reason as in #925, the algorithm of `SimBA` requires probabilities as predictions. Your method `predict` returns one-hot encoded predictions, because of that `SimBa` cannot estimate gradients.

**Comment by taylover2016** [comment]
Well, I came across the same problem. I suppose it's because the iteration is limited to 30, while the default is 3000, so it may need more iteration.

**Comment by Code-Ranger** [comment]
Hello beat-buesser,
I have modified my predict() method to return probabilities instead of one-hot result (please find it in the  below). But I still can't generate the working adv examples (ResNet still classify the examples as correct one) with the argument you recommeded. And even with iter = 3000 as recommeded by taylover2016, it still not working.

Could you give me some more hints on how to make the SimBA code working?
Thanks very much!


```
def predict(x):
    global predict_counter
    predict_counter += 1

    x = np.array(x[0])
    # convert np array back to image
    img = Image.fromarray(x.astype(np.uint8))
    # save the image to
    img.save(os.path.join("/home/ranger/lizhu/data/adv/SimBA", str(predict_counter).zfill(5) + '.jpg'))

    img_t = preprocess(img)
    batch_t = torch.unsqueeze(img_t, 0)
    resnet.eval()
    output = resnet(batch_t)
    return output.detach().numpy()
```

**Comment by beat-buesser** [comment]
Hi @Code-Ranger  Could you please provide a reproducible example in a Google Colab notebook? I'd be interested to try it out.

**Comment by beat-buesser** [comment]
@Code-Ranger @taylover2016 What are the parameters you are using for `max_iter`, `freq_dim`, `order`, and `stride`?

**Comment by beat-buesser** [comment]
@Code-Ranger I noticed your new function `predict` returns now logits, but `SimBa` is expecting probabilities as output. And `epsilon` needs to be defined relative to the range of `x` which in your case is [0, 255], `epsilon`'s default value is for range [0, 1].

**Comment by taylover2016** [comment]
@beat-buesser I set the max_iter to 30 due to the limitation of computing resources, and epsilon is 0.1. But the other params are set as default. But according to your last reply, maybe it's because I return the logits rather than the probabilities. The range of x is already [0, 1] though.

**Comment by taylover2016** [comment]
@beat-buesser So if the algorithm requires the `predict` to return probabilities(such as Square Attack and SimBA), then it can't be logits but needs to be the probabilities derived from logits?

**Comment by taylover2016** [comment]
I tried with the normalized probabilities again, using F.softmax().
Sadly there's only change in prediction for the first photo, and still the perturbation is not strong enough to cause misclassification.

My  `predict` function is as follows:

def predict(data):
    """tensor_data = torch.from_numpy(data)
    probability = F.softmax(
        input=model(tensor_data),
        dim=1
    )

    probability_numpy = probability.detach().numpy()"""
    logits_numpy = classifier.predict(data)
    logits = torch.from_numpy(logits_numpy)
    probability = F.softmax(
        input=logits,
        dim=1
    )
    probability_numpy = probability.detach().numpy()
    return probability_numpy

and this is my setting for the SimBA attacker:

attacker = SimBA(
    classifier=BlackBox,
    max_iter=300,
    epsilon=0.1
)

**Comment by taylover2016** [comment]
I tried with the normalized probabilities again, using F.softmax().
Sadly there's only change in prediction for the first photo, and still the perturbation is not strong enough to cause misclassification.

My  `predict` function is as follows:

def predict(data):
    logits_numpy = classifier.predict(data)
    logits = torch.from_numpy(logits_numpy)
    probability = F.softmax(
        input=logits,
        dim=1
    )
    probability_numpy = probability.detach().numpy()
    return probability_numpy

and this is my setting for the SimBA attacker:

attacker = SimBA(
    classifier=BlackBox,
    max_iter=300,
    epsilon=0.1
)

**Comment by beat-buesser** [comment]
> @beat-buesser I set the max_iter to 30 due to the limitation of computing resources, and epsilon is 0.1. But the other params are set as default. But according to your last reply, maybe it's because I return the logits rather than the probabilities. The range of x is already [0, 1] though.

Yes, your method `predict` has to return probabilities.

You also need to increase the values of `freq_dim` and `stride` to values higher than the default values.

It would be helpful if you could share a complete notebook of your example, in my reconstruction of the experiment based on your code above `target_image` provided to `attack,generate` is in range [0, 255] therefore you have to increase `epsilon` accordingly, e.g. `0.1*255`.

`SimBa.generate` does not support the argument `x_adv_init` for initialisation and restarts, it should just be ` x_adv = attack.generate(x=np.array([target_image]))` instead of ` x_adv = attack.generate(x=np.array([target_image]), x_adv_init=x_adv)` and no for loop.

With the changes above, the attack was successful for me with these values: `max_iter = 500`, `freq_dim = 28`, `order = "random"`, `stride = 4`, `epsilon = 25` for an image of class 377 (marmoset).

**Comment by beat-buesser** [comment]
> @beat-buesser So if the algorithm requires the `predict` to return probabilities(such as Square Attack and SimBA), then it can't be logits but needs to be the probabilities derived from logits?

Yes, `SimBa` requires probabilities, e.g. from a softmax function on the existing logits of your model.

`SquareAttack` requires logits as model output as discuss recently in #925.

**Comment by taylover2016** [comment]
Well I tried just now, with the probabilities derived from the Softmax layer. 
Sadly though, it's even worse than using the logits, which bothers me a lot. 
Also due to the limitation of my computational resources, I'll probably not try max_iter larger than 100. For several times I can even smell that my laptop is going to burn lol.
But one thing I should probably point out is that, my image is normalized after the loading process. So there's no need for scaling the epsilon, I think.
And thanks for providing the params. It's just, I may not dive into that and see what's really going on since both the White-Box Auto-PGD and the Black-Box Square Attack work fine.

Again, huge thanks for your kind support. I really appreciate it. It means a lot.

**Comment by beat-buesser** [comment]
Hi @taylover2016 Thank you very much and please let us know when you have more questions! Ok, if the images provided to `attack.generate` is in range [0, 1] then and `epsilon=0.1` should work. Yes, for this model and images I need around 300-500 iterations for `SimBA` to find an adversarial example.
