### ISSUE TITLE
SVC and LR ValueError: The number of classes has to be greater than one; got 1 class

### ISSUE THREAD

**Issue by matthew-64** [Trusted-AI/adversarial-robustness-toolbox#983]
Hi all, 

I am trying to transfer some existing sklearn models (RF and SVM) into the art toolbox to preform some binary classification. The existing models work as expected before I tried to use them as part of the ART toolbox. 

However the following error arrives once I try to use the sklearn wrapper class as such:

```
from sklearn.linear_model import LogisticRegression
from art.estimators.classification import SklearnClassifier

model = LogisticRegression(C=0.1, penalty='l2', solver='lbfgs', multi_class='ovr')))
art_model = SklearnClassifier(model)

data, target = read_train_data()
art_model.fit(data, target)
```

the `.fit(...)` will produce the following error:

```
Traceback (most recent call last):
  File "/Users/matthew/Desktop/uni_work/project/NIDS_Masters_Project/local_testing/adversarial.py", line 239, in <module>
    classifier.fit(data, target)
  File "/Users/matthew/Desktop/uni_work/project/NIDS_Masters_Project/venv/lib/python3.7/site-packages/art/estimators/classification/classifier.py", line 71, in replacement_function
    return fdict[func_name](self, *args, **kwargs)
  File "/Users/matthew/Desktop/uni_work/project/NIDS_Masters_Project/venv/lib/python3.7/site-packages/art/estimators/classification/scikitlearn.py", line 156, in fit
    self.model.fit(x_preprocessed, y_preprocessed, **kwargs)
  File "/Users/matthew/Desktop/uni_work/project/NIDS_Masters_Project/venv/lib/python3.7/site-packages/sklearn/ensemble/_voting.py", line 292, in fit
    return super().fit(X, transformed_y, sample_weight)
  File "/Users/matthew/Desktop/uni_work/project/NIDS_Masters_Project/venv/lib/python3.7/site-packages/sklearn/ensemble/_voting.py", line 82, in fit
    for idx, clf in enumerate(clfs) if clf != 'drop'
  File "/Users/matthew/Desktop/uni_work/project/NIDS_Masters_Project/venv/lib/python3.7/site-packages/joblib/parallel.py", line 1041, in __call__
    if self.dispatch_one_batch(iterator):
  File "/Users/matthew/Desktop/uni_work/project/NIDS_Masters_Project/venv/lib/python3.7/site-packages/joblib/parallel.py", line 859, in dispatch_one_batch
    self._dispatch(tasks)
  File "/Users/matthew/Desktop/uni_work/project/NIDS_Masters_Project/venv/lib/python3.7/site-packages/joblib/parallel.py", line 777, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/Users/matthew/Desktop/uni_work/project/NIDS_Masters_Project/venv/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/Users/matthew/Desktop/uni_work/project/NIDS_Masters_Project/venv/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/Users/matthew/Desktop/uni_work/project/NIDS_Masters_Project/venv/lib/python3.7/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/Users/matthew/Desktop/uni_work/project/NIDS_Masters_Project/venv/lib/python3.7/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/Users/matthew/Desktop/uni_work/project/NIDS_Masters_Project/venv/lib/python3.7/site-packages/sklearn/utils/fixes.py", line 222, in __call__
    return self.function(*args, **kwargs)
  File "/Users/matthew/Desktop/uni_work/project/NIDS_Masters_Project/venv/lib/python3.7/site-packages/sklearn/ensemble/_base.py", line 39, in _fit_single_estimator
    estimator.fit(X, y)
  File "/Users/matthew/Desktop/uni_work/project/NIDS_Masters_Project/venv/lib/python3.7/site-packages/sklearn/svm/_base.py", line 173, in fit
    y = self._validate_targets(y)
  File "/Users/matthew/Desktop/uni_work/project/NIDS_Masters_Project/venv/lib/python3.7/site-packages/sklearn/svm/_base.py", line 560, in _validate_targets
    " class" % len(cls))
ValueError: The number of classes has to be greater than one; got 1 class
```

The same error can be reproduced using the following model:
`model = SVC(kernel='linear', C=0.001, gamma=0.0001, probability=True)`

**The data I passed in was a series of 1 and 0. Thus, there was more than 1 class.**

I would like to reiterate that this error is only observed when using the ScikitlearnSVC wrapper class. I have looked for a solution to this but have not yet found one. Any help would be greatly appreciated.

Additional information:
* python3.7
* adversarial-robustness-toolbox==1.6.0
* sklearn==0.0
* scikit-learn==0.24.1

Regards,
Matthew

**Comment by beat-buesser** [comment]
Hi @matthew-64 Thank you very much for using ART! Up to the current version of ART 1.6.0 you will have to provide the labels `y` one-hot encoded with shape (nb_samples, nb_classes) to the ART estimators for scikit-learn models.

We see a lot of interest in binary classification and its more common index labels format, therefore we are working on supporting index labels for binary classification with ART 1.7 in connection with #306.

**Comment by matthew-64** [comment]
Hey @beat-buesser, thank you for the help! You solved my problem.

**Comment by beat-buesser** [comment]
@matthew-64 That's great to hear, thank you!
